### ISSUE TITLE
Multi-dimensional array as input

### ISSUE THREAD

**Issue by sanchopansa** [akosba/xjsnark#18]
Is it possible to specify a multi-dimensional array as an input to the SNARK in xjsnark?

Something like:
```java
public uint_32[][] m = new uint_32[2][16];
...
inputs { 
  m 
}
```

I tried a couple of variations of the above, but I always seem to get "Variable reference type not supported/allowed to be labelled".

**Comment by akosba** [comment]
Hi, I added support for using multi-dimensional arrays as inputs/outputs or witnesses with an example. For some technical difficulties, this is limited to 3 dimensions at this point. 
Thanks
