### ISSUE TITLE
`Make Project` fails

### ISSUE THREAD

**Issue by bl4ck5un** [akosba/xjsnark#19]
@akosba  Hope you're well, Ahmed! 

I tried `Make project` in MPS (the correct version) but got the following errors during "pre-generate validation". 

![screenshot from 2019-03-07 14-53-39](https://user-images.githubusercontent.com/2434648/53985174-f5af2f80-40e8-11e9-8010-1f435a2b81cc.png)

Ignoring the errors doesn't work.

![screenshot from 2019-03-07 14-56-45](https://user-images.githubusercontent.com/2434648/53985304-458df680-40e9-11e9-84c8-1803ce505a70.png)

Did I miss anything?

**Comment by akosba** [comment]
Hi Fan, Thanks. Hope you're well too!  

This seems to be working at my end, so let me verify the following: 
- Did you try to rebuild the xjsnark project itself before doing make project to AES? Did you face any errors while doing so? 
- Does this problem only appear in the AES case?  
- Do you use the MPS version listed in the readme without installing any updates?

**Comment by bl4ck5un** [comment]
- I was rebuilding the xjsnark project not AES.
- No.
- Yes.

But, I find a solution! One just needs to Rebuild the whole project twice. It succeeds in the 2nd compilation. Here is a screencast showing the process:

[xjsnark2.mkv.zip](https://github.com/akosba/xjsnark/files/2943338/xjsnark2.mkv.zip)

**Comment by akosba** [comment]
I see. There is a way no to do this twice. What I do first is to build the language extension itself first (The language module marked with L). I have that listed in the readme, but probably I should clarify that this does not mean the whole project, as building the whole project will try to build the sandbox solution first.

**Comment by bl4ck5un** [comment]
Oh, I see. I confused the language extension with the project name.

We might need to write a simple TLS packet parser as part of a circuit (the input is a TLS packet. I know it may sound crazy). xjsnark seems a good tool to use. Any suggestion/caveat?

**Comment by akosba** [comment]
For implementing parsing in circuits, you might find the Cinderella paper relevant: https://www.andrew.cmu.edu/user/bparno/papers/cinderella.pdf . I recall they had to handle the issue of variable-length fields in ASN.1 parsing, but I don't have an example now showing how this can be done in the most efficient way in jsnark or xjsnark, but I expect it should be doable. (Implementing this in xJsnark might require some care in choosing the types of your variables. For example, in some situations, using the native field types could be more efficient than integer types, but this all depends on the context and the operations you're implementing. I hope to make a tutorial at some point.)
Feel free to email me any time you have more questions about this.

**Comment by bl4ck5un** [comment]
Wow! you really know this stuff well. Thanks for the link. I'll give it a try.
