### ISSUE TITLE
How to reproduce a model & Cleanup

### ISSUE THREAD

**Issue by mskd12** [akosba/xjsnark#20]
Hi Ahmed,

I was wondering how to reproduce a model. Is the .mps file the only thing required for reproducing the circuit? If so, I wonder why there are so many `trace.info` and various other files in `languages/xjsnark/source_gen/*` and `languages/xjsnark/source_gen.caches/*` for example?

**Comment by akosba** [comment]
Hi Deepak, yes, the .mps files are what's need for reproducing the circuits. I removed the old unneeded files.

**Comment by mskd12** [comment]
Thanks, Ahmed!
