### ISSUE TITLE
Integer division and conversion to field element

### ISSUE THREAD

**Issue by sanchopansa** [akosba/xjsnark#23]
Hi, Ahmed!

As part of a project I'm working on, I think I might have hit an issue in the library. I've isolated the issue and I'm including the program below for reference. Let me know if you would also like the model file:

```java
Program IntDivisionTest { 
 
  public F_p x; 
  public F_p y; 
  public F_p output; 
   
  inputs { 
    << ... >> 
  } 
  outputs { 
    output  
  } 
  witnesses_AssertRange { 
    << ... >>  
  } 
  witnesses { 
    x, y  
  } 
   
   
  public void outsource() {  
    F_p prod = x * y; 
    output = F_p(uint_254(prod) / uint_4(10));
  } 
   
   
  SampleRun("Sample_Run1", true){ 
    pre { 
        x.val = new BigInteger("4294967295"); 
        y.val = new BigInteger("1"); 
    } 
    post { 
        <no statements> 
    } 
  } 
   
   
   
  public static void main(string[] args) { 
    Config.hexOutputEnabled = false; 
  } 
}
```

The program above produces the expected result, provided that `prod` is less than `2^32`. So, the example I included will work, as the product is exactly `2^32 - 1`, but if I increase `x` by one, I get the following error (output truncated for succinctness):

```
Running Sample Run: Sample_Run1
Evaluating Input on the circuit 
	[input] Value of Wire # 0 (The one-input wire.) :: 1
0*1!=4294967296
Error - Assertion Failed assert in 2 <332 0> out 1 <4> 		# Equality assertion of long elements | case 2 | index 0
Exception in thread "main" java.lang.RuntimeException: Error During Circuit Evaluation
	at backend.operations.primitive.AssertBasicOp.compute(AssertBasicOp.java:29)
	at backend.operations.primitive.BasicOp.evaluate(BasicOp.java:71)
	at backend.eval.CircuitEvaluator.evaluate(CircuitEvaluator.java:160)
	at backend.structure.CircuitGenerator.__evaluateSampleRun(CircuitGenerator.java:463)
	at xjsnark.test.IntDivisionTest.<init>(IntDivisionTest.java:27)
	at xjsnark.test.IntDivisionTest.main(IntDivisionTest.java:21)

Process finished with exit code 1
```

Do you have any idea what might be the issue or maybe I'm doing something wrong here?

Thank you!

**Comment by sanchopansa** [comment]
Thank you, Ahmed! I can confirm that the above fix has resolved the issue.

**Comment by akosba** [comment]
Hi Valentin, 
Thanks for reporting the issue. The code for equality assertions did not account for the case that one of the operands might have been a long element instantiated from a native field element (this is similar to issue 22, but a different method), so I pushed a fix. By the way, I later pushed a follow up update for one of the sanity checks that I added with the above fix, as it was too restrictive for other use cases, so please update to the latest version.
