### ISSUE TITLE
what are the exact formulas for calculating the matrice elements Lo, Co, Ro, Go, Rs, Gd?

### ISSUE THREAD

**Issue by aliceglitch** [akosba/xjsnark#27]
How the matrices on page 96 of the PDF are calculated? In other words, to calculate each of the Elements of Lo, Co, Ro, Go, Rs, Gd matrices, formulas out there? thank you.
[hspice_si.pdf](https://github.com/akosba/xjsnark/files/5361216/hspice_si.pdf)

**Comment by akosba** [comment]
This is not related to this repository. This issue will be deleted.
