### ISSUE TITLE
Arrays of struct instances cannot be passed as inputs

### ISSUE THREAD

**Issue by m1cm1c** [akosba/xjsnark#35]
I'm not entirely sure whether this is a bug or I'm just unable to figure this out. However, I've tried to get this to work for a long time and haven't figured it out.

When passing a struct as in input, it seems that you need to create a global variable and call `new` like so:

```
private StructName variableName = new StructName();
```

In the sample run, you then need to assign values to the struct's elements like so:

```
variableName.elementName.val = new BigInteger("3");
variableName.anotherElementName.val = new BigInteger("17");
```

However, I cannot figure out how to extend this to arrays of structs.

The only way I even got it to compile was by defining a global array

```
private StructName[] arrayName = new StructName[10];
```

and then initializing the array elements in the sample run:

```
for(int i = 0; i < 10; i++) {
  arrayName[i] = new StructName();
  arrayName[i].elementName.val = new BigInteger("3");
  arrayName[i].anotherElementName.val = new BigInteger("17");
}
```

However, I know that initializing structs in the sample run does not work for regular (non-array) variables. And in fact, while code written like this does compile, it crashes with a NullPointerException as soon as the struct's elements are accessed for the first time in function `outsource()`.

If it is possible to have arrays of structs as inputs, it would be nice to have a short code snippet showing how it is done added to the documentation. If it is not possible, the documentation should contain a note that it just is not possible.

**Comment by akosba** [comment]
Yes, it is possible to have arrays of structs as inputs. As you have noticed already and as shown in the Zerocash example, the input struct instances need to be instantiated outside outsource().
When you have an array of structs, both the array need to be instantiated, and every individual struct instance. This is similar to what's expected when using arrays of objects in java. 
The way to do the instantiation outside the outsource method is using the initializer blocks. Here is a quick example:

```
struct ExampleStruct { 
    uint_32 x; 
}


Program ArrayOfStructs { 
 
  private ExampleStruct[] array = new ExampleStruct[10]; 
  { 
    for (int i = 0; i < 10; i++) { 
      array[i] = new ExampleStruct(); 
    } 
  } 
   
  uint_32 sum; 
   
  inputs { 
    array 
  } 
  outputs { 
    sum  
  } 
   
  public void outsource() { 
    sum = 0; 
    for (int i = 0; i < 10; i++) { 
      sum = sum + array[i].x; 
    } 
  } 
   
   
  SampleRun("Sample_Run1", true){ 
    pre { 
        for (int i = 0; i < 10; i++) { 
          array[i].x.val = BigInteger.valueOf(10); 
        } 
    } 
    post { 
        <no statements> 
    } 
  } 
}
```

I hope this helps. I will push a note and an example later to clarify this. Thank you.
